#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

#配置mybatis
mybatis:
  typeAliasesPackage: com.boot.demo.bootdemo.domain
  mapper-locations: classpath:mapper/*.xml

#配置mapper
mapper:
  not-empty: false
  identity: MYSQL

#配置Tomcat，配置80，可在浏览器访问项目时不用加端口号（默认端口8080）
server:
  port: 80